Attestation metadata update + Improving types on score
vacekj/regenscore pull request #119
Opened 2023-10-17 00:30 UTC by mateodaza

2023-10-17 00:30 UTC, mateodaza commented
#116

2023-10-17 07:54 UTC, vacekj commented on src/bulkScore.ts
> +    const row: any = [
no any please 🙂

2023-10-17 07:57 UTC, vacekj commented on src/helpers/scoreHelpers.ts
> -  // handleNormalTransactions,
same as above - either remove or uncomment if needed.

2023-10-17 07:58 UTC, vacekj commented on src/helpers/scoreHelpers.ts
>      // erc721Transactions:null,
⬆️

2023-10-17 08:00 UTC, vacekj commented on src/helpers/sourceTypes.ts
> +    ethDeposits?: any[];
no-any

2023-10-17 08:00 UTC, vacekj commented on src/helpers/sourceTypes.ts
> +    opBridges?: any[];
no-any

2023-10-17 08:00 UTC, vacekj commented on src/helpers/sourceTypes.ts
> +    transfers?: any[];
no-any

2023-10-17 08:00 UTC, vacekj commented on src/helpers/sourceTypes.ts
> +    passport?: any;
no-any

2023-10-17 08:01 UTC, vacekj commented on src/hooks/useEAS.ts
> +    meta: any,
no-any

2023-10-17 08:01 UTC, vacekj commented on src/hooks/useEAS.ts
> +    scoreData: any,
no-any

2023-10-17 08:02 UTC, vacekj requested changes
Great work - there are some `any` left and some commented out code to delete, but otherwise lgtm. I'll aprove asap after those are fixed.

2023-10-21 22:23 UTC, mateodaza commented
@vacekj thanks for reviewing, fixes are done :)

2023-10-22 21:11 UTC, vacekj approved these changes

2023-10-22 21:14 UTC, merged